In [3]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2026.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (6.33.5)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 18.0 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.1.0-py3-none-any.whl (155 kB)
Downloading websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance

   ---------------------------------------- 0/5 [peewee]
   ---------------- ----------------------- 2/5 [websockets]
   ------------------------ --------------- 3/5 [curl_cffi]
   -------------------------------- ------- 4/5 [yfinance]
   ---------------------------------------- 5/5 [yfinance]

Successfully installed curl_cffi-0.15.0 multitasking-0.0.13 peewee-4.1.0 websockets-16.0 yfinance-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import yfinance as yf
import numpy as np
import pandas as pd

In [39]:
# import data from ticker 

ydf = yf.download("NVDA",
                  start="2015-01-01",
                  end="2026-04-30",
                  progress=False)

In [40]:
print(f"Downloaded {len(ydf)} rows of data.")

Downloaded 2847 rows of data.

In [41]:
ydf

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2015-01-02    0.482423    0.486018    0.474754    0.482423  113680000
2015-01-05    0.474275    0.483861    0.472118    0.482423  197952000
2015-01-06    0.459895    0.475473    0.459416    0.474994  197764000
2015-01-07    0.458697    0.467325    0.457259    0.463251  321808000
2015-01-08    0.475952    0.478828    0.463730    0.463970  283780000
...                ...         ...         ...         ...        ...
2026-04-23  199.407593  203.592718  196.990412  202.224317  113561800
2026-04-24  208.027542  210.704415  199.577384  199.727219  214134400
2026-04-27  216.357834  216.577579  207.138583  209.405930  187172400
2026-04-28  212.921844  214.480026  207.957629  209.246136  180275400
2026-04-29  209.006409  212.472370  207.338355  212.452389  123711800

[2847 rows x 5 columns]

In [9]:
ydf.columns

MultiIndex([( 'Close', 'NVDA'),
            (  'High', 'NVDA'),
            (   'Low', 'NVDA'),
            (  'Open', 'NVDA'),
            ('Volume', 'NVDA')],
           names=['Price', 'Ticker'])

In [58]:
# Create column for the length of the candle body and daily price action
ydf['Candle_Body'] = (ydf[('Close', 'NVDA')] - ydf[('Open', 'NVDA')]).abs()
ydf['Total price action'] = (ydf[('High', 'NVDA')] - ydf[('Low', 'NVDA')])

# Create a column to determine if Candle is bullish or bearish 
ydf['Bullish/Bearish'] = np.where((ydf['Close', 'NVDA'] > ydf['Open', 'NVDA']), 'Bullish', 'Bearish')

# Create column for candle body percentage
ydf['Body %'] = (ydf['Candle_Body'] / ydf['Total price action']) * 100

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,
Date,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,69.387800
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,79.364899
...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,67.120571

In [60]:
ydf.sort_index(inplace=True)
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,
Date,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,69.387800
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,79.364899
...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,67.120571

In [67]:
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,
Date,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,69.387800
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,79.364899
...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,67.120571

In [72]:
#Add 5, 10, 20, 50, and 200 day EMA Columns 

ydf['5_EMA'] = ydf['Close', 'NVDA'].ewm(span=5, adjust=False).mean()
ydf['10_EMA'] = ydf['Close', 'NVDA'].ewm(span=10, adjust=False).mean()
ydf['20_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()
ydf['50_EMA'] = ydf['Close', 'NVDA'].ewm(span=50, adjust=False).mean()
ydf['200_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,,
Date,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,79.364899,0.470852,0.474164,0.477431,0.480177,0.477431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,42.662739,199.743683,196.414477,190.964749,186.173520,190.964749
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225

In [50]:
ydf['Body %'] = body_df.style.format({'Body': '{:.1%}'})

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,
Date,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,<pandas.io.formats.style.Styler object at 0x00...
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,<pandas.io.formats.style.Styler object at 0x00...
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,<pandas.io.formats.style.Styler object at 0x00...
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,<pandas.io.formats.style.Styler object at 0x00...
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,<pandas.io.formats.style.Styler object at 0x00...
...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,<pandas.io.formats.style.Styler object at 0x00...
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,<pandas.io.formats.style.Styler object at 0x00...
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,<pandas.io.formats.style.Styler object at 0x00...
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,<pandas.io.formats.style.Styler object at 0x00...
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,<pandas.io.formats.style.Styler object at 0x00...

In [26]:
pip install TA-lib

Collecting TA-libNote: you may need to restart the kernel to use updated packages.

  Downloading ta_lib-0.6.8-cp313-cp313-win_amd64.whl.metadata (24 kB)
Collecting build (from TA-lib)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy in C:\Users\mcm4g\anaconda3\Lib\site-packages (from TA-lib) (2.4.6)
Requirement already satisfied: packaging>=24.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (26.0)
Collecting pyproject_hooks (from build->TA-lib)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (0.4.6)
Downloading ta_lib-0.6.8-cp313-cp313-win_amd64.whl (887 kB)
   ---------------------------------------- 0.0/887.6 kB ? eta -:--:--
   ---------------------------------------- 887.6/887.6 kB 8.9 MB/s  0:00:00
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pyproject_hooks, build, TA-lib

   ------------- -------------------------- 1/3 [build]
   -------------------------- ------------- 2/3 [TA-lib]
   ---------------------------------------- 3/3 [TA-lib]

Successfully installed TA-lib-0.6.8 build-1.5.0 pyproject_hooks-1.2.0

In [25]:
this can be used to compare columns 
ydf.shift()

Price,Close,High,Low,Open,Volume,Candle_Body
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,
Date,,,,,,
2015-01-02,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,0.482423,0.486018,0.474754,0.482423,113680000.0,0.000000
2015-01-06,0.474275,0.483861,0.472118,0.482423,197952000.0,0.008148
2015-01-07,0.459896,0.475473,0.459416,0.474994,197764000.0,0.015098
2015-01-08,0.458697,0.467325,0.457259,0.463251,321808000.0,0.004553
...,...,...,...,...,...,...
2025-12-23,183.466232,183.935661,182.127868,183.695948,129064400.0,0.229716
2025-12-24,188.979523,189.099372,182.677196,182.747118,174873600.0,6.232404
2025-12-26,188.380234,188.679871,186.362690,187.711052,65528500.0,0.669182
2025-12-29,190.297897,192.455270,187.770981,189.688640,139740300.0,0.609258
2025-12-30,187.990707,188.530043,185.683524,187.481334,120006100.0,0.509373

In [10]:
ydf['Low']

Ticker            NVDA
Date
2015-01-02    0.474754
2015-01-05    0.472118
2015-01-06    0.459416
2015-01-07    0.457259
2015-01-08    0.463730
...                ...
2025-12-23  182.677196
2025-12-24  186.362690
2025-12-26  187.770981
2025-12-29  185.683524
2025-12-30  186.702281

[2765 rows x 1 columns]

In [11]:
pip install nasdaq-data-link

Collecting nasdaq-data-linkNote: you may need to restart the kernel to use updated packages.

  Downloading Nasdaq_Data_Link-1.0.4-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: pandas>=0.14 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.2.3)
Requirement already satisfied: numpy>=1.8 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.4.6)
Requirement already satisfied: requests>=2.7.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.34.2)
Requirement already satisfied: inflection>=0.3.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (0.5.1)
Requirement already satisfied: python-dateutil in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.9.0.post0)
Requirement already satisfied: six in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (1.17.0)
Requirement already satisfied: more-itertools in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (11.0.2)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2026.5.20)
Downloading Nasdaq_Data_Link-1.0.4-py2.py3-none-any.whl (28 kB)
Installing collected packages: nasdaq-data-link
Successfully installed nasdaq-data-link-1.0.4

In [36]:
import nasdaqdatalink as ndl

In [37]:
My_Nas_Key = "bp9V2Fn_MCJ8xEUxYS8p"

ndl.ApiConfig.api_key = My_Nas_Key

In [42]:
df = ndl.get_table("NVDA")

DataLinkError: (Status 404) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@data.nasdaq.com.