In [1]:
pip install yfinance

Requirement already satisfied: yfinance in C:\Users\mcm4g\anaconda3\Lib\site-packages (1.4.1)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.34.2)
Requirement already satisfied: multitasking>=0.0.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2026.2)
Requirement already satisfied: peewee>=3.16.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (6.33.5)
Requirement already satisfied: websockets>=13.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install vectorbt

Requirement already satisfied: vectorbt in C:\Users\mcm4g\anaconda3\Lib\site-packages (1.0.0)
Requirement already satisfied: numpy>=1.23 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (2.4.6)
Requirement already satisfied: pandas<3.0,>=2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (2.2.3)
Requirement already satisfied: scipy in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (1.17.1)
Requirement already satisfied: matplotlib in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (3.10.0)
Requirement already satisfied: plotly>=4.12.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (5.24.1)
Requirement already satisfied: ipywidgets>=7.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (8.1.5)
Requirement already satisfied: anywidget in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (0.11.0)
Requirement already satisfied: numba>=0.60 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (0.65.1)
Requirement already satisfied: dill in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (0.3.8)
Requirement already satisfied: tqdm in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (4.67.3)
Requirement already satisfied: dateparser in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (1.4.1)
Requirement already satisfied: imageio in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (2.37.0)
Requirement already satisfied: scikit-learn in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (1.6.1)
Requirement already satisfied: schedule in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (1.2.2)
Requirement already satisfied: requests in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (2.34.2)
Requirement already satisfied: pytz in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (2026.2)
Requirement already satisfied: mypy_extensions in C:\Users\mcm4g\anaconda3\Lib\site-packages (from vectorbt) (1.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas<3.0,>=2.0->vectorbt) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas<3.0,>=2.0->vectorbt) (2025.2)
Requirement already satisfied: comm>=0.1.3 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (8.30.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (5.15.0)
Requirement already satisfied: widgetsnbextension~=4.0.12 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (4.0.13)
Requirement already satisfied: jupyterlab_widgets~=3.0.12 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (3.0.13)
Requirement already satisfied: decorator in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (5.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.19.2)
Requirement already satisfied: matplotlib-inline in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (2.20.0)
Requirement already satisfied: stack-data in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.0)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.4.6)
Requirement already satisfied: wcwidth in C:\Users\mcm4g\anaconda3\Lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.8.4)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from numba>=0.60->vectorbt) (0.47.0)
Requirement already satisfied: tenacity>=6.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from plotly>=4.12.0->vectorbt) (9.0.0)
Requirement already satisfied: packaging in C:\Users\mcm4g\anaconda3\Lib\site-packages (from plotly>=4.12.0->vectorbt) (26.0)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=2.0->vectorbt) (1.17.0)
Requirement already satisfied: psygnal>=0.8.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from anywidget->vectorbt) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from anywidget->vectorbt) (4.15.0)
Requirement already satisfied: regex>=2024.9.11 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from dateparser->vectorbt) (2024.11.6)
Requirement already satisfied: tzlocal>=0.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from dateparser->vectorbt) (5.4.4)
Requirement already satisfied: pillow>=8.3.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from imageio->vectorbt) (12.2.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from matplotlib->vectorbt) (1.3.1)
Requirement already satisfied: cycler>=0.10 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from matplotlib->vectorbt) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from matplotlib->vectorbt) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from matplotlib->vectorbt) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from matplotlib->vectorbt) (3.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->vectorbt) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->vectorbt) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->vectorbt) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->vectorbt) (2026.5.20)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from scikit-learn->vectorbt) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from scikit-learn->vectorbt) (3.5.0)
Requirement already satisfied: executing in C:\Users\mcm4g\anaconda3\Lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.8.3)
Requirement already satisfied: asttokens in C:\Users\mcm4g\anaconda3\Lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (3.0.0)
Requirement already satisfied: pure-eval in C:\Users\mcm4g\anaconda3\Lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install TA-lib

Requirement already satisfied: TA-lib in C:\Users\mcm4g\anaconda3\Lib\site-packages (0.6.8)
Requirement already satisfied: build in C:\Users\mcm4g\anaconda3\Lib\site-packages (from TA-lib) (1.5.0)
Requirement already satisfied: numpy in C:\Users\mcm4g\anaconda3\Lib\site-packages (from TA-lib) (2.4.6)
Requirement already satisfied: packaging>=24.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (26.0)
Requirement already satisfied: pyproject_hooks in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (1.2.0)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [4]:
!pip install --upgrade statsmodels

Requirement already satisfied: statsmodels in C:\Users\mcm4g\anaconda3\Lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from statsmodels) (2.4.6)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [5]:
!pip install fredapi pandas

Requirement already satisfied: fredapi in C:\Users\mcm4g\anaconda3\Lib\site-packages (0.5.2)
Requirement already satisfied: pandas in C:\Users\mcm4g\anaconda3\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import scipy
import statsmodels.api as sm

In [7]:
import yfinance as yf
import numpy as np
import pandas as pd
import talib
from datetime import datetime

In [8]:
# import data from ticker 

ydf = yf.download("NVDA",
                  start="2015-01-01",
                  end="2026-04-30",
                  progress=False)

In [9]:
print(f"Downloaded {len(ydf)} rows of data.")

Downloaded 2847 rows of data.

In [10]:
ydf

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2015-01-02    0.482423    0.486018    0.474754    0.482423  113680000
2015-01-05    0.474275    0.483861    0.472118    0.482423  197952000
2015-01-06    0.459896    0.475473    0.459416    0.474994  197764000
2015-01-07    0.458697    0.467325    0.457259    0.463251  321808000
2015-01-08    0.475952    0.478828    0.463730    0.463970  283780000
...                ...         ...         ...         ...        ...
2026-04-23  199.407593  203.592718  196.990412  202.224317  113561800
2026-04-24  208.027542  210.704415  199.577384  199.727219  214134400
2026-04-27  216.357834  216.577579  207.138583  209.405930  187172400
2026-04-28  212.921844  214.480026  207.957629  209.246136  180275400
2026-04-29  209.006409  212.472370  207.338355  212.452389  123711800

[2847 rows x 5 columns]

In [11]:
ydf.columns

MultiIndex([( 'Close', 'NVDA'),
            (  'High', 'NVDA'),
            (   'Low', 'NVDA'),
            (  'Open', 'NVDA'),
            ('Volume', 'NVDA')],
           names=['Price', 'Ticker'])

In [12]:
# Create column for the length of the candle body and daily price action (Total candle range)
ydf['Candle_Body'] = (ydf[('Close', 'NVDA')] - ydf[('Open', 'NVDA')]).abs()
ydf['Total price action'] = (ydf[('High', 'NVDA')] - ydf[('Low', 'NVDA')])

# Create a column to determine if Candle is bullish, bearish or a doji
doji = abs(ydf['Close', 'NVDA'] - ydf['Open', 'NVDA']) <= (0.10 * (ydf['High', 'NVDA'] - ydf['Close', 'NVDA']))
ydf['Bullish/Bearish'] = np.where(
    doji,
    'Doji',
    np.where((ydf['Close', 'NVDA'] > ydf['Open', 'NVDA']), 'Bullish', 'Bearish')
)

# Create column for candle body percentage by dividing the candle body by the total price action of the day
ydf['Body %'] = (ydf['Candle_Body'] / ydf['Total price action']) * 100

# Change total price action column to Candle_range 

ydf = ydf.rename(columns={'Total price action': 'Candle_Range'})

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,
Date,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899
...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571

In [13]:
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,
Date,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899
...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571

In [14]:
#Add 5, 10, 20, 50, and 200 day EMA Columns 

ydf['5_EMA'] = ydf['Close', 'NVDA'].ewm(span=5, adjust=False).mean()
ydf['10_EMA'] = ydf['Close', 'NVDA'].ewm(span=10, adjust=False).mean()
ydf['20_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()
ydf['50_EMA'] = ydf['Close', 'NVDA'].ewm(span=50, adjust=False).mean()
ydf['200_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,
Date,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,0.474164,0.477431,0.480176,0.477431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,196.414476,190.964749,186.173519,190.964749
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225

In [15]:
import talib

In [16]:
ydf['RSI'] = talib.RSI(ydf['Close', 'NVDA'])
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA,RSI
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,,
Date,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423,NaN
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647,NaN
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575,NaN
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587,NaN
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,0.474164,0.477431,0.480176,0.477431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,196.414476,190.964749,186.173519,190.964749,64.645031
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777,71.498288
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401,76.282915
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205,70.989369
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225,65.418381

In [17]:
import vectorbt as vbt

In [18]:
#Calculate the upper wick by subtracking the high from either the open or close. Use max function and axis=1 to choose the option closest to the upperwick
ydf['Upper_wick'] = abs(ydf['High', 'NVDA'] - ydf[[('Open', 'NVDA'), ('Close', 'NVDA')]].max(axis=1))
# Caculate the same for the lower wick using the min function with axis=1 so it chooses the value closest to the lower wick between the open and close
ydf['Lower_wick'] = abs(ydf['Low', 'NVDA'] - ydf[[('Open', 'NVDA'), ('Close', 'NVDA')]].min(axis=1))

# Calculate wick percentage by dividing the absolute value of the upper or lower wick by the candle ranage (total candle length)
ydf['Upper_wick_percentage'] = abs(ydf['Upper_wick'] / ydf['Candle_Range']) * 100
ydf['Lower_wick_percentage'] = abs(ydf['Lower_wick'] / ydf['Candle_Range']) * 100

# Calculate Wick to body ratio by dividing the sum of the wicks by the candle body
ydf['Wick_to_body_ratio'] = (ydf['Lower_wick'] + ydf['Upper_wick']) / ydf['Candle_Body']

# Calsulate the gap size 
ydf['gap_size'] = ydf['Open', 'NVDA'] - ydf['Close', 'NVDA'].shift(1)
# Calculate gap percentage 
ydf['gap_percentage'] = (ydf['gap_size'] / ydf['Close', 'NVDA'].shift(1)) * 100

# Caluclate distance from EMA distnace Percentage 
ydf['5EMA_touched'] = np.where((ydf['5_EMA'] >= ydf['Low', 'NVDA']) & (ydf['5_EMA'] <= ydf['High', 'NVDA']), 'True', 'False')
ydf['10EMA_touched'] = np.where((ydf['10_EMA'] >= ydf['Low', 'NVDA']) & (ydf['10_EMA'] <= ydf['High', 'NVDA']), 'True', 'False')
ydf['20EMA_touched'] = np.where((ydf['20_EMA'] >= ydf['Low', 'NVDA']) & (ydf['20_EMA'] <= ydf['High', 'NVDA']), 'True', 'False')
ydf['50EMA_touched'] = np.where((ydf['50_EMA'] >= ydf['Low', 'NVDA']) & (ydf['50_EMA'] <= ydf['High', 'NVDA']), 'True', 'False')
ydf['200EMA_touched'] = np.where((ydf['200_EMA'] >= ydf['Low', 'NVDA']) & (ydf['200_EMA'] <= ydf['High', 'NVDA']), 'True', 'False')
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,...,Upper_wick_percentage,Lower_wick_percentage,Wick_to_body_ratio,gap_size,gap_percentage,5EMA_touched,10EMA_touched,20EMA_touched,50EMA_touched,200EMA_touched
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,...,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,...,31.915002,68.084998,inf,NaN,NaN,True,True,True,True,True
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,...,12.244977,18.367223,0.441176,-7.587153e-08,-0.000016,True,True,True,True,True
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,...,2.985040,2.985040,0.063491,7.190050e-04,0.151601,True,False,False,False,False
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,...,40.476326,14.285795,1.210537,3.355084e-03,0.729532,False,False,False,False,False
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,...,19.047727,1.587374,0.260003,5.272421e-03,1.149434,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,...,20.726097,36.611164,1.343966,-3.994972e-02,-0.019751,True,False,False,False,False
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,...,24.057386,1.346581,0.340554,3.196261e-01,0.160288,True,False,False,False,False
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,...,2.328056,24.021056,0.357757,1.378388e+00,0.662599,False,False,False,False,False
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,...,23.889707,19.755112,0.774460,-7.111698e+00,-3.287007,True,False,False,False,False
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,...,0.389188,32.490241,0.489856,-4.694550e-01,-0.220482,True,False,False,False,False

In [20]:
%pip install python-dotenv

Requirement already satisfied: python-dotenv in C:\Users\mcm4g\anaconda3\Lib\site-packages (1.2.1)
Note: you may need to restart the kernel to use updated packages.

In [32]:
pip install cpi

Collecting cpi
  Downloading cpi-2.0.10-py2.py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: requests in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.34.2)
Requirement already satisfied: click in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (8.2.1)
Requirement already satisfied: python-dateutil in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.9.0.post0)
Requirement already satisfied: pandas in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.2.3)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from click->cpi) (0.4.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2.4.6)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil->cpi) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (2026.5.20)
Downloading cpi-2.0.10-py2.py3-none-any.whl (18.1 MB)
   ---------------------------------------- 0.0/18.1 MB ? eta -:--:--
   ----- ---------------------------------- 2.4/18.1 MB 18.5 MB/s eta 0:00:01
   ----------------- ---------------------- 8.1/18.1 MB 22.6 MB/s eta 0:00:01
   -------------------------------- ------- 14.9/18.1 MB 27.4 MB/s eta 0:00:01
   ---------------------------------------- 18.1/18.1 MB 26.5 MB/s  0:00:00
Installing collected packages: cpi
Successfully installed cpi-2.0.10
Note: you may need to restart the kernel to use updated packages.

In [47]:
pip install --upgrade cpi

Requirement already satisfied: cpi in C:\Users\mcm4g\anaconda3\Lib\site-packages (2.0.10)
Requirement already satisfied: requests in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.34.2)
Requirement already satisfied: click in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (8.2.1)
Requirement already satisfied: python-dateutil in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.9.0.post0)
Requirement already satisfied: pandas in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cpi) (2.2.3)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from click->cpi) (0.4.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2.4.6)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas->cpi) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil->cpi) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests->cpi) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.

In [48]:
import cpi

In [49]:
df_cpi = cpi_series.to_dataframe()
df_cpi

,series_id,year,date,value,period_id,period_code,period_abbreviation,period_name,period_month,period_type
0,CUUR0000SA0,1997,1997-01-01,159.1,M01,M01,JAN,January,1,monthly
1,CUUR0000SA0,1997,1997-02-01,159.6,M02,M02,FEB,February,2,monthly
2,CUUR0000SA0,1997,1997-03-01,160.0,M03,M03,MAR,March,3,monthly
3,CUUR0000SA0,1997,1997-04-01,160.2,M04,M04,APR,April,4,monthly
4,CUUR0000SA0,1997,1997-05-01,160.1,M05,M05,MAY,May,5,monthly
...,...,...,...,...,...,...,...,...,...,...
1468,CUUR0000SA0,1996,1996-09-01,157.8,M09,M09,SEP,September,9,monthly
1469,CUUR0000SA0,1996,1996-10-01,158.3,M10,M10,OCT,October,10,monthly
1470,CUUR0000SA0,1996,1996-11-01,158.6,M11,M11,NOV,November,11,monthly
1471,CUUR0000SA0,1996,1996-12-01,158.6,M12,M12,DEC,December,12,monthly
1472,CUUR0000SA0,1996,1996-01-01,156.9,M13,M13,AN AV,Annual Average,1,annual

In [22]:
ndf = yf.download("NVDA",
                  start="2015-01-01",
                  end="2026-04-30",
                  progress=False)
ndf

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2015-01-02    0.482423    0.486018    0.474754    0.482423  113680000
2015-01-05    0.474275    0.483861    0.472118    0.482423  197952000
2015-01-06    0.459896    0.475473    0.459416    0.474994  197764000
2015-01-07    0.458697    0.467325    0.457259    0.463251  321808000
2015-01-08    0.475952    0.478828    0.463730    0.463970  283780000
...                ...         ...         ...         ...        ...
2026-04-23  199.407593  203.592718  196.990412  202.224317  113561800
2026-04-24  208.027542  210.704415  199.577384  199.727219  214134400
2026-04-27  216.357834  216.577579  207.138583  209.405930  187172400
2026-04-28  212.921844  214.480026  207.957629  209.246136  180275400
2026-04-29  209.006409  212.472370  207.338355  212.452389  123711800

[2847 rows x 5 columns]

In [23]:
ndf['5_EMA'] = talib.EMA(ndf['Close', 'NVDA'].to_numpy(), timeperiod=20)
ndf

Price,Close,High,Low,Open,Volume,5_EMA
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,
Date,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,NaN
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,NaN
2015-01-06,0.459896,0.475473,0.459416,0.474994,197764000,NaN
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,NaN
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,NaN
...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,190.964749
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,192.589777
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,194.853401
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,196.574205
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,197.758225

In [24]:
ydf['20)

SyntaxError: unterminated string literal (detected at line 1) (4034197693.py, line 1)

In [ ]:
this can be used to compare columns based on differnt days 

ydf.shift()

In [ ]:
ydf['Low']

In [ ]:
pip install nasdaq-data-link

In [ ]:
import nasdaqdatalink as ndl

In [ ]:
My_Nas_Key = "bp9V2Fn_MCJ8xEUxYS8p"

ndl.ApiConfig.api_key = My_Nas_Key

In [ ]:
ndf